PhotoContest/PhotoContest/PhotoContest.Web/Controllers/ContestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using PhotoContest.Data;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.Models;
using PhotoContest.Services.Models.Create;
using PhotoContest.Services.Models.Update;
using PhotoContest.Services.Services;
using PhotoContest.Web.Models.ContestViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class ContestsController : Controller
    {
        private readonly PhotoContestContext _context;
        private readonly IContestService contestService;
        private readonly ICategoryService categoryService;
        private readonly SignInManager<User> signInManager;
        private readonly IUserContestService userContestService;
        private readonly IPhotoService photoService;
        private readonly IUserService userService;
        private readonly IToastNotification toastNotification;

        public ContestsController(PhotoContestContext context,
                                  IContestService contestService,
                                  ICategoryService categoryService,
                                  SignInManager<User> signInManager,
                                  IUserContestService userContestService,
                                  IPhotoService photoService,
                                  IUserService userService,
                                  IToastNotification toastNotification)
        {
            _context = context;
            this.contestService = contestService;
            this.categoryService = categoryService;
            this.signInManager = signInManager;
            this.userContestService = userContestService;
            this.photoService = photoService;
            this.userService = userService;
            this.toastNotification = toastNotification;
        }

        /// <summary>
        /// Get all contests
        /// </summary>
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var contests = await this.contestService.GetAllAsync();
            if (User.IsInRole("User"))
            {
                return RedirectToAction("AllOpen");
            }
            else
                return View(contests.Select(c => new ContetsViewModel(c)));
        }

        /// <summary>
        /// Get all open contests
        /// </summary>
        /// <returns>Return a list with all open contests</returns>
        [Authorize]
        public async Task<IActionResult> AllOpen()
        {
            var contests = await this.contestService.AllOpenViewAsync();
            var userContests = await this.userContestService.GetAllUserContestsAsync();
            var photos = await this.photoService.GetAllAsync();
            var juries = await this.contestService.GetAllJuriesAsync();
            return View(contests.Select(c => new ContetsViewModel(c) { AllUserContests = userContests, AllPhotos = photos.ToList(), Juries = juries.ToList() }));
        }

        /// <summary>
        /// Filter all open contests
        /// </summary>
        /// <param name="status">Phase of the contests to filter by</param>
        /// <returns>A list of all open contests after filtering</returns>
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> GetOpenFiltered(string status)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var contests = await this.contestService.GetAllOpenAsync(status);
                    var userContests = await this.userContestService.GetAllUserContestsAsync();
                    var photos = await this.photoService.GetAllAsync();
                    var juries = await this.contestService.GetAllJuriesAsync();
                    return View(contests.Select(c => new ContetsViewModel(c) { AllUserContests = userContests, AllPhotos = photos.ToList(), Juries = juries.ToList() }));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString() + status;
                    return Redirect(path);
                }
            }
            return View();
        }

        /// <summary>
        /// Get details of a contest
        /// </summary>
        /// <param name="name">Name of the contest</param>
        [Authorize]
        public async Task<IActionResult> Details(string name)
        {
            var contest = await this.contestService.FindContestByNameAsync(name);
            var userContests = await this.userContestService.GetAllUserContestsAsync();
            var photos = await this.photoService.GetAllAsync();
            var juries = await this.contestService.GetAllJuriesAsync();
            var contestDTO = new ContestDTO(contest);
            return View(new ContetsViewModel(contestDTO) { AllUserContests = userContests, AllPhotos = photos.ToList(), Juries = juries.ToList() });
        }

        /// <summary>
        /// Show a for to create a contest
        /// </summary>
        [Authorize(Roles = "Admin, Organizer")]
        public async Task<IActionResult> Create()
        {
            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Create a contest
        /// </summary>
        /// <param name="createViewModel">Details of the contest to create</param>
        /// <returns>To list of all contests if successful or go to error page for bad request</returns>
        [Authorize(Roles = "Admin, Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateContestViewModel createViewModel)
        {
            var newContestDTO = new NewContestDTO()
            {
                Name = createViewModel.Name,
                CategoryName = createViewModel.CategoryName,
                IsOpen = createViewModel.IsOpen,
                Phase1 = createViewModel.Phase1,
                Phase2 = createViewModel.Phase2,
                Finished = createViewModel.Finished
            };

            if (ModelState.IsValid)
            {
                try
                {
                    await this.contestService.CreateAsync(newContestDTO);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    return Redirect(Request.Path.Value.ToString());
                }
            }
            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Show for to edit a contest
        /// </summary>
        /// <param name="name">Name of the contest to edit</param>
        [Authorize(Roles = "Admin, Organizer")]
        public async Task<IActionResult> Edit(string name)
        {
            var contest = await this.contestService.FindContestByNameAsync(name);
            var updateContestDTO = new EditContestViewModel();

            updateContestDTO.Name = contest.Name;
            updateContestDTO.Category = contest.Category.Name;
            updateContestDTO.IsContestOpen = contest.IsOpen;
            updateContestDTO.Phase1 = contest.Phase1.ToString("dd.MM.yy HH:mm");
            updateContestDTO.Phase2 = contest.Phase2.ToString("dd.MM.yy HH:mm");
            updateContestDTO.Finished = contest.Finished.ToString("dd.MM.yy HH:mm");

            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View(updateContestDTO);
        }

        /// <summary>
        /// Edit a contest
        /// </summary>
        /// <param name="name">Name of the contest to edit</param>
        /// <param name="editViewModel">Details to edit</param>
        /// <returns>To list of all contests if successful or go to error page for bad request</returns>
        [Authorize(Roles = "Admin, Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string name, EditContestViewModel editViewModel)
        {
           
            if (ModelState.IsValid)
            {
                try
                {
                    var updateContestDTO = new UpdateContestDTO();
                    updateContestDTO.CategoryName = editViewModel.Category;
                    updateContestDTO.IsOpen = editViewModel.IsContestOpen;
                    updateContestDTO.Phase1 = editViewModel.Phase1;
                    updateContestDTO.Phase2 = editViewModel.Phase2;
                    updateContestDTO.Finished = editViewModel.Finished;
                    await this.contestService.UpdateAsync(name, updateContestDTO);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString() + "?name=" + editViewModel.Name;
                    return Redirect(path);
                }
            }
            var categories = await this.categoryService.GetAllBaseAsync();
            ViewData["Categories"] = new SelectList(categories, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Get a contest to delete
        /// </summary>

PhotoContest/PhotoContest/PhotoContest.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.Models;
using PhotoContest.Services.Services;
using PhotoContest.Web.Models;
using PhotoContest.Web.Models.HomeViewModels;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IContestService contestService;
        private readonly IPhotoService photoService;

        public HomeController(ILogger<HomeController> logger, IContestService contestService, IPhotoService photoService)
        {
            _logger = logger;
            this.contestService = contestService;
            this.photoService = photoService;
        }

        /// <summary>
        /// Home page of the website
        /// </summary>
        /// <returns>List of latest winning photos and list of newest contests</returns>
        public async Task<IActionResult> Index()
        {
            var allContests = await this.contestService.GetAllAsync();
            var phase1Contests = allContests.Where(c => c.Status == "Phase 1" && c.OpenOrInvitational == "Open");
            var photos = await this.photoService.GetAllBaseAsync();
            var finishedContests = await this.contestService.GetAllFinishedContestsAsync();
            var photosFirstPlaces = new List<PhotoDTO>();

            foreach (var contest in finishedContests)
            {
                foreach (var photo in photos)
                {
                    if (photo.Contest.Name == contest.Name)
                    {
                        photosFirstPlaces.Add(new PhotoDTO(photo));
                        break;
                    }
                }
            }
            return View(new HomeContestsViewModel()
            {
                PhotosFirstPlace = photosFirstPlaces,
                Phase1Contests = phase1Contests.ToList()
            });
        }

        /// <summary>
        /// Shows the privacy page of the website
        /// </summary>
        public IActionResult Privacy()
        {
            return View();
        }

        /// <summary>
        /// Error page of the website 404 Not found
        /// </summary>
        public IActionResult PageNotFound()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PhotoContest/PhotoContest/PhotoContest.Web/Views/Home/Index.cshtml
@model HomeContestsViewModel

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@{
    ViewData["Title"] = "Home Page";
}
@section Styles{
    <link rel="stylesheet" href="~/css/1.css">
}
@section Scripts{
    <script src="~/js/2js.js"></script>
    <script src="~/js/3js.js"></script>
    <script src="~/js/4js.js"></script>
}

<div class="text-center">
    <div class="jumbotron">
        <h1 class="display-3">Welcome to the world of photography</h1>
        <br />
        <p class="lead">
            <h3>Show your skills and compete to win</h3>
        </p>
    </div>
</div>

<div class="text-center">
    <h3>Latest winning photos</h3>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div id="inam" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="container">
                            <div class="row">
                                @foreach (var item in Model.PhotosFirstPlace.Take(3))
                                {
                                    <partial name="_SinglePhotoPartial" model="new PhotoViewModel(item)" />
                                }
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="container">
                            <div class="row">
                                @foreach (var item in Model.PhotosFirstPlace.Skip(3).Take(3))
                                {
                                    <partial name="_SinglePhotoPartial" model="new PhotoViewModel(item)" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a href="#inam" class="carousel-control-prev" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a href="#inam" class="carousel-control-next" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
</div>
<br />

<div class="text-center">
    <h3>Present contests you can participate in</h3>
</div>
<div class="container-fluid text-center" >
    <div class="row">
        <div class="col-sm-12">
            <div id="inam" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner ">
                    <div class="carousel-item active ">
                        <div class="container ">
                            <div class="row">
                                @foreach (var item in Model.Phase1Contests.Take(3))
                                {
                                    <div class="col-sm-12 col-lg-4">
                                        <div class="card" style="background-color:khaki;" margin: auto;">
                                            <div class="card-body">
                                                <h4 class="card-title">@item.Name</h4>
                                                <p class="card-text">Category: @item.Category</p>
                                            </div>
                                            @if (SignInManager.IsSignedIn(User))
                                            {
                                                <a class="btn btn-dark" asp-action="Details" asp-controller="Contests" asp-route-name="@item.Name">Details</a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Details</a>
                                            }
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="container">
                            <div class="row">
                                @foreach (var item in Model.Phase1Contests.Skip(3).Take(3))
                                {
                                    <div class="col-sm-12 col-lg-4">
                                        <div class="card" style="background-color:khaki;" margin: auto;">
                                            <div class="card-body">
                                                <h4 class="card-title">@item.Name</h4>
                                                <p class="card-text">Category: @item.Category</p>
                                                <div class="align-items-center">
                                                </div>
                                            </div>
                                            @if (SignInManager.IsSignedIn(User))
                                            {
                                                <a class="btn btn-dark" asp-action="Details" asp-controller="Contests" asp-route-name="@item.Name">Details</a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Details</a>
                                            }
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <a href="#inam" class="carousel-control-prev" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a href="#inam" class="carousel-control-next" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
</div>

PhotoContest/PhotoContest/PhotoContest.Web/Views/Home/PageNotFound.cshtml
<img class="align-content-center" style="position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%);" src="~/Images/404.jpg" alt="page not found" />