PhotoContest/PhotoContest/PhotoContest.Web/Controllers/PhotosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.Models.Create;
using PhotoContest.Services.Models.Update;
using PhotoContest.Services.Services;
using PhotoContest.Web.Models.PhotoViewModels;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class PhotosController : Controller
    {
        private readonly IPhotoService photoService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IContestService contestService;
        private readonly IReviewService reviewService;
        private readonly IToastNotification toastNotification;

        public PhotosController(IPhotoService photoService,
            IWebHostEnvironment webHostEnvironment,
            IContestService contestService,
            IReviewService reviewService,
            IToastNotification toastNotification)
        {
            this.photoService = photoService;
            this.webHostEnvironment = webHostEnvironment;
            this.contestService = contestService;
            this.reviewService = reviewService;
            this.toastNotification = toastNotification;
        }

        /// <summary>
        /// Get all photos
        /// </summary>
        /// <returns>List of all photos</returns>
        [Authorize(Roles = "Admin,Organizer")]
        public async Task<IActionResult> Index()
        {
            var photos = await this.photoService.GetAllAsync();
            return View(photos.Select(p => new PhotoViewModel(p)));
        }

        /// <summary>
        /// Get contest to upload a photo to
        /// </summary>
        /// <param name="contestName">Contest in which the photo will be uploaded</param>
        [Authorize(Roles = "Admin,User")]
        public IActionResult Create(string contestName)
        {
            var createPhotoVM = new CreatePhotoViewModel()
            {
                ContestName = contestName
            };
            return View(createPhotoVM);
        }

        /// <summary>
        /// Upload a photo in a contest
        /// </summary>
        /// <param name="model">Details of the photo to upload</param>
        /// <returns>List of all user's contests or error page if bad request</returns>
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePhotoViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var newFileName = $"{Guid.NewGuid()}_{model.File.FileName}";
                    var fileDbPath = $"/Images/{newFileName}";
                    var saveFile = Path.Combine(webHostEnvironment.WebRootPath, "Images", newFileName);
                    using (var fileSelected = new FileStream(saveFile, FileMode.Create))
                    {
                        await model.File.CopyToAsync(fileSelected);
                    }
                    using (var img = Image.Load(model.File.OpenReadStream()))
                    {
                        img.Mutate(x => x.Resize(400, 400));
                        //img.Save(fileDbPath);
                    }

                    var newPhotoDTO = new NewPhotoDTO()
                    {
                        Title = model.Title,
                        Description = model.Description,
                        PhotoUrl = fileDbPath,
                        ContestName = model.ContestName
                    };


                    await this.photoService.CreateAsync(newPhotoDTO);
                    return RedirectToAction("GetUserContests", "Contests");
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString() + "?contestName=" + model.ContestName;
                    return Redirect(path); 
                }
            }
            return View(model);
        }

        /// <summary>
        /// Show photos for signed in user
        /// </summary>
        [Authorize(Roles = "User")]
        public async Task<IActionResult> GetPhotosForUser()
        {
            var photos = await this.photoService.GetPhotosForUserAsync();
            return View(photos.Select(p => new PhotoViewModel(p) { ContestStatus = p.ContestStatus }));
        }

        /// <summary>
        /// Get photos for a contets
        /// </summary>
        /// <param name="contestName">name of the contest</param>
        /// <returns>List of all photos for a contest</returns>
        [Authorize]
        public async Task<IActionResult> GetContestsPhotos(string contestName)
        {
            try
            {
                var reviews = await this.reviewService.GetAllReviewsAsync();
                var photos = await this.photoService.GetPhotosForContestAsync(contestName);
                var contest = await this.contestService.FindContestByNameAsync(contestName);
                var juries = await this.contestService.GetAllJuriesAsync();
                return View(photos.Select(p => new PhotoViewModel(p) { ContestStatus = contest.Status.Name, Juries = juries, Reviews = reviews }));
            }
            catch (Exception)
            {
                return RedirectToAction("PageNotFound", "Home");
            }
        }

        /// <summary>
        /// Get a photo to edit
        /// </summary>
        /// <param name="id">Id of the photo</param>
        [Authorize(Roles = "Admin,Organizer")]
        public async Task<IActionResult> Edit(Guid id)
        {
            try
            {
                var photo = await this.photoService.GetAsync(id);
                return View(new EditPhotoViewModel(photo));
            }
            catch (Exception)
            {
                return RedirectToAction("PageNotFound", "Home");
            }
        }

        /// <summary>
        /// Edit a photo
        /// </summary>
        /// <param name="id">Id of the photo to edit</param>
        /// <param name="model">Details of the photo to edit</param>
        /// <returns>Returns list of all photos or error page if bad request</returns>
        [Authorize(Roles = "Admin,Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, EditPhotoViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var updateDTO = new UpdatePhotoDTO()
                    {
                        Title = model.Title,
                        Description = model.Description
                    };
                    var photo = await this.photoService.UpdateAsync(updateDTO, id);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString()+model.Id;
                    return Redirect(path);
                }
            }
            return View(model);
        }

        /// <summary>
        /// Get photo to delete
        /// </summary>
        /// <param name="id">Id of the photo</param>
        [Authorize(Roles = "Admin,Organizer")]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                var photo = await this.photoService.GetAsync(id);
                return View(new PhotoViewModel(photo));
            }
            catch (Exception)
            {
                return RedirectToAction("PageNotFound", "Home");
            }
        }

        /// <summary>
        /// Delete a photo
        /// </summary>
        /// <param name="id">Id of the photo</param>
        /// <returns>List of all photos or error page if bad request</returns>
        [Authorize(Roles = "Admin,Organizer")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                /*var photo = await this.photoService.GetAsync(id);
                var imagePath = Path.Combine(webHostEnvironment.WebRootPath, photo.PhotoUrl);
                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }*/
                await this.photoService.DeleteAsync(id);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                return View(id);
            }
        }
    }
}

PhotoContest/PhotoContest/PhotoContest.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PhotoContest.Services.Contracts;
using PhotoContest.Services.Models;
using PhotoContest.Services.Models.Create;
using PhotoContest.Services.Models.Update;
using PhotoContest.Web.Models.UserViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace PhotoContest.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        private readonly IToastNotification toastNotification;

        public UsersController(IUserService userService,IToastNotification toastNotification)
        {
            this.userService = userService;
            this.toastNotification = toastNotification;
        }

        /// <summary>
        /// Get all users
        /// </summary>
        /// <returns>List of those users</returns>
        [Authorize(Roles = "Admin,Organizer")]
        public async Task<IActionResult> Index()
        {
            var users = await this.userService.GetAllAsync();
            return View(users.Select(u=>new UserViewModel(u)));
        }

        /// <summary>
        /// Get all users participating i na contest
        /// </summary>
        /// <returns>List of those users</returns>
        [Authorize(Roles = "Admin,Organizer")]
        public async Task<IActionResult> ViewAllParticipants()
        {
            var users = await this.userService.GetAllParticipantsAsync();
            return View(users.Select(u => new UserViewModel(u)));
        }

        /// <summary>
        /// Show form to create organizer
        /// </summary>
        [Authorize(Roles = "Admin")]
        public IActionResult CreateOrganizer()
        {
            return View();
        }

        /// <summary>
        /// Create organizer
        /// </summary>
        /// <param name="model">Details of the organizer</param>
        /// <returns>List of users or error page if bad request</returns>
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrganizer(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var newUserDTO = new NewUserDTO()
                    {
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Email = model.Email,
                        EmailConfirmed = model.EmailConfirmed,
                        Password = model.Password
                    };
                    var user = await this.userService.CreateOrganizerAsync(newUserDTO);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    return View();
                }
            }
            return View();
        }

        /// <summary>
        /// Get user to edit
        /// </summary>
        /// <param name="username">Username of the user</param>
        [Authorize(Roles = "Admin,Organizer")]
        public async Task<IActionResult> Edit(string username)
        {
            try
            {
                var user = await this.userService.GetUserByUsernameAsync(username);
                var userDTO = new UserDTO(user);
                return View(new EditUserViewModel(userDTO));
            }
            catch (Exception)
            {
                return RedirectToAction("PageNotFound", "Home");
            }
        }

        /// <summary>
        /// Edit user
        /// </summary>
        /// <param name="username">Username of the user</param>
        /// <param name="model">Details to update</param>
        /// <returns>List of all users or error page if bad request</returns>
        [Authorize(Roles = "Admin,Organizer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string username, EditUserViewModel model)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var updateUserDTO = new UpdateUserDTO()
                    {
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                    };
                    await this.userService.UpdateAsync(updateUserDTO, username);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    toastNotification.AddErrorToastMessage(e.Message, new NotyOptions());
                    var path = Request.Path.Value.ToString() + "?Username=" + model.Username;
                    return Redirect(path);
                }
            }
            return View();
        }

        /// <summary>
        /// Get user to delete
        /// </summary>
        /// <param name="username">Username of the user</param>
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string username)
        {
            try
            {
                var user = await this.userService.GetUserByUsernameAsync(username);
                var userDTO = new UserDTO(user);
                return View(new UserViewModel(userDTO));
            }
            catch (Exception)
            {
                return RedirectToAction("PageNotFound", "Home");
            }
        }

        /// <summary>
        /// Delete user
        /// </summary>
        /// <param name="username">Username of the user</param>
        /// <returns>List of all users or error page if bad request</returns>
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string username)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await this.userService.DeleteAsync(username);
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return RedirectToAction("PageNotFound", "Home");
                }
            }
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Get user by username
        /// </summary>
        [Authorize(Roles = "Admin,Organizer")]
        public IActionResult SearchByUsername()
        {
            return View();
        }

        /// <summary>
        /// Show details about user
        /// </summary>
        /// <param name="model">Username of the user</param>
        /// <returns>Details of the user or error page if bad request</returns>
        [Authorize(Roles = "Admin,Organizer,User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ShowUserInfo(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await this.userService.GetUserByUsernameAsync(model.Username);
                    var userDTO = new UserDTO(user);
                    var userViewModel = new UserViewModel(userDTO);
                    return View(userViewModel);
                }
                catch (Exception)
                {
                    return RedirectToAction("PageNotFound", "Home");
                }
            }
            return View();
        }

        /// <summary>
        /// Get details for signed in user
        /// </summary>
        [Authorize]
        public async Task<IActionResult> ShowMyAccountInfo()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var userDTO = await this.userService.ShowMyAccountInfo();
                    var userViewModel = new UserViewModel(userDTO);
                    return View(userViewModel);
                }
                catch (Exception)
                {
                    return RedirectToAction("PageNotFound", "Home");
                }
            }
            return View();
        }
    }
}

PhotoContest/PhotoContest/PhotoContest.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<meta property="og:url" content="https://www.your-domain.com/your-page.html" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Your Website Title" />
        <meta property="og:description" content="Your description" />
        <meta property="og:image" content="https://www.your-domain.com/path/image.jpg" />*@
    <title>@ViewData["Title"] - PhotoContest.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color:khaki; font-weight:bold; font-size:1rem;">
            <div class="container">
               <a href="@Url.Action("Index","Home")">
                   <img src="@Url.Content("~/Images/logoPhotoContest.png")", style="height:60px; width:60px" alt="Index"/>
                   </a>
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhotoContest</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User) && (User.IsInRole("Organizer") || User.IsInRole("Admin")))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contests" asp-action="Index">Contests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="Index">Photos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contests" asp-action="AllOpen">Contests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contests" asp-action="GetUserContests">My Contests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="GetPhotosForUser">My photos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="ShowMyAccountInfo">My account</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PhotoContest.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("NToastNotify")
    @RenderSection("Scripts", required: false)
</body>
</html>

PhotoContest/PhotoContest/PhotoContest.Web/Views/Shared/_SinglePhotoPartial.cshtml
@model PhotoViewModel
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@section Styles{
    <link href="~/css/site.css" rel="stylesheet" />
}

<div class="card text-light bg-dark" style="width: 300px; margin: auto;">
    <img class="img-fluid" src="@Model.PhotoUrl" alt="Card image cap">
    <div class="card-body text-center">
        <h5 class="card-title">@Model.Title</h5>
        <h6 class="card-title">Points: @Model.Points</h6>
        <p class="card-subtitle">Owner: @Model.User</p>
        <p class="card-subtitle">Contest: @Model.Contest</p>
        <p class="card-subtitle">Category: @Model.Category</p>
        @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
        {
            if (Model.ContestStatus == "Finished")
            {
                <a asp-controller="Reviews" asp-action="GetPhotoReviews" class="btn btn-light" asp-route-id="@Model.Id">Reviews</a>
            }
            else if (Model.ContestStatus == "Phase 2" && Model.Juries.Any(j => j.Contest.Name == Model.Contest && j.User.UserName == UserManager.GetUserName(this.SignInManager.Context.User)))
            {
                <a class="btn btn-success" asp-controller="Reviews" asp-action="Create" asp-route-photoId="@Model.Id">Rate</a>
            }
            else if (Model.ContestStatus == "Phase 2" && Model.Reviews.Any(r => r.Evaluator.UserName == UserManager.GetUserName(this.SignInManager.Context.User) && r.PhotoId == Model.Id))
            {
                <p class="text-danger">You have already rated this photo.</p>
            }
        }
        else if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {
            @if (Model.ContestStatus == "Phase 2")
            {
                <a class="btn btn-success" asp-controller="Reviews" asp-action="Create" asp-route-photoId="@Model.Id">Rate</a>
            }
            else if (Model.ContestStatus == "Finished")
            {
                <a asp-controller="Reviews" asp-action="GetPhotoReviews" class="btn btn-light" asp-route-id="@Model.Id">Reviews</a>
            }
            <a class="btn btn-light" asp-action="Edit" asp-controller="Photos" asp-route-id="@Model.Id">Edit</a>
            <a class="btn btn-danger" asp-action="Delete" asp-controller="Photos" asp-route-id="@Model.Id">Delete</a>
        }
        else if (SignInManager.IsSignedIn(User) && User.IsInRole("Organizer"))
        {
            @if (Model.ContestStatus == "Phase 2")
            {
                if (Model.Reviews.Any(r => r.Evaluator.UserName == UserManager.GetUserName(this.SignInManager.Context.User) && r.PhotoId == Model.Id))
                {
                    <p class="text-danger">You have already rated this photo.</p>
                }
                else
                {
                    <a class="btn btn-success" asp-controller="Reviews" asp-action="Create" asp-route-photoId="@Model.Id">Rate</a>
                }
            }
            else if (Model.ContestStatus == "Finished")
            {
                <a asp-controller="Reviews" asp-action="GetPhotoReviews" class="btn btn-light" asp-route-id="@Model.Id">Reviews</a>
            }
            <a class="btn btn-light" asp-action="Edit" asp-controller="Photos" asp-route-id="@Model.Id">Edit</a>
        }
    </div>
</div>
@section Scripts{
}